### PR TITLE
add rss template to include full content from projects and blogs

### LINKED ISSUE #216: Publish properly formed RSS feed
## User story
As an enjoyer of blogs I need to be able to find the RSS feed link so that I can get updated when new posts are made without relying on social media announcements and algorithm roulette.

## Acceptance criteria

- [ ] RSS feed is properly sorted
- [ ] RSS feed shows fulltext
- [ ] RSS feed shows only blog posts and new portfolio stuff?
- [ ] Add RSS link to socials bit in footer 

## Implementation notes & questions

- http://gfsc.studio/index.xml
- this is hugos default, do we want to modify it at all?
- is the socials link the best place?

### PR DESCRIPTION
**Pull request by aaaaargZombies**
Fixes #216 

## Description

- [x] RSS feed is properly sorted
- [x] RSS feed shows fulltext
- [x] RSS feed shows only blog posts and new portfolio stuff?
- [x] Add RSS link to socials bit in footer

### CODE REVIEW

**Comment by kimadactyl** [comment]
The only issue I see here is that project dates look like when projects began, so when we add them noone will see them.

Prob the simplest fix is to remove project for now until we can think about this? Otherwise they prob all need like a "publication date"? If we set them all to say, 1st Feb 2023 tho it will give a weird idea about our RSS feed to new people. Ideas?

**Comment by aaaaargZombies** [comment]
I should say anything that is marked as draft just got a dummy date.

`date` in frontmatter corresponds to `<pubDate>Wed, 07 Dec 2022 00:00:00 +0000</pubDate>` in RSS so is effectively what you describe, it's only read by the rss template.

I just pulled the other dates from the `when` field so they didn't clump together.  I think that these dates are good enough to sit in a timeline and that we should set the date we publish a page as we add other projects.

I'm wary of renaming this field because it's shared by the blog frontmatter too.

**Comment by kimadactyl** [comment]
hmm. just for consistancy can we set a date field on all the non-draft projects? something probably like a month after the end of the timescale given? im not sure we should be getting date info from 2 places tht both work differently

**Comment by aaaaargZombies** [comment]
ok I think everything now has an approximate date, I still think it would be good to update the `date` to the day you switch `draft` from `true` to `false` so RSS subscribers get it at the top of the feed but at least if someone forgets now it will fall in a non-broken position.

> im not sure we should be getting date info from 2 places tht both work differently

yeah this is a bit confusing but `when` field is just text on a subject, it's not really an accurate date we can do computational stuff with.

**Review by kimadactyl — APPROVED** [review]
looks great thanks for bearing with me!

**Pull request merged**
