### PR TITLE
projects show tags

### LINKED ISSUE #268: Add tags to project index page
## Description

Projects should contain a list of tags to show which categories & themes they belong to

(current)

Screenshot 2023-06-28 at 13 57 36

(proposed)

(ignore spacing, this is a rough sketch and is a change to add tags only!)

Screenshot 2023-06-28 at 13 57 28

https://www.figma.com/file/rLewb9kn4mUt8lLI0wuC7f/GFSC?type=design&node-id=245-314&mode=design&t=fQa9SLXXAEXhPLPT-0

## Acceptance criteria
- [ ] I can see a list of tags on a project page
- [ ] I can click on a tag to visit the index page for that tag

### PR DESCRIPTION
**Pull request by aaaaargZombies**
Fixes #268

## Description

- show tags on the main project page
- I added another box because it felt a bit lost without but I'm happy to get rid of it

https://0ed34d02.gfsc.pages.dev/project/placecal/

note: I spawned a branch from main and rebased my other open pr into this one so I could work in parallel sorry it's dragged so many commits in. If this is an acceptable design I'll tidy it up before merging  :crossed_fingers:

@geeksforsocialchange/developers

### CODE REVIEW

**Comment by aaaaargZombies** [comment]
@undividual It would be good to get your input on this, see link in description for a preview

**Comment by undividual** [comment]
(PS sorry if those other bits are outside the scope of this ticket!)

**Review by ivan-kocienski-gfsc — APPROVED** [review]
Looks good to me.

**Comment by aaaaargZombies** [comment]
>  I know I proabbly designed it like this, but I think text should align all the way down on the left. With that in mind, can we bring client and team inwards to line up with the main body of the article?

@undividual do you want to make this into a new issue if it's a new problem you've spotted, it is out of scope for what I'm working on ATM as we're touching lots of different places where themes are involved in the site rather than going page by page.

**Pull request closed without merging**
