### PR TITLE
Feat/263 add filter buttons

### LINKED ISSUE #266: Add new filter buttons to enable selecting by theme from our work page
## Description

There is an option to filter by theme or filter by category at the top of `our work` page

Screenshot 2023-06-28 at 15 11 02

https://www.figma.com/file/rLewb9kn4mUt8lLI0wuC7f/GFSC?type=design&node-id=245-314&mode=design&t=Z2mPZRvdBT84zJ01-0

## Acceptance criteria
- [x] I can select filter by category (name tbc) or filter by theme from two buttons at the top
- [x] When I hover over a button it fills in from left to right like other buttons on the site
- [x] The selected category button is filled in orange like the selected tab is in the top of the site
- [x] Selecting a button shows a range of categories or themes to choose from which are laid out in the same way that categories currently are
- [x] clicking on a category or a theme takes me to that category or theme's index page

### PR DESCRIPTION
**Pull request by r-ferrier**
Fixes #266

## Description

- Adds filter buttons onto the our work page

@geeksforsocialchange/developers

### CODE REVIEW

**Comment by aaaaargZombies** [comment]
A few questions / thoughts.

- Should we `aria-live` the changing list? This is the main issue for me.
- I'd prefer the styles to be in the CSS something like `.btn--active` and `.hidden` and use `toggle` on the `classList` https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle but not blocking for me.
- I thought `[].map` returned a new array and `[].forEach` mutated existing arrays so I was surprised this worked, but it does so I'll have to look into that!

**Comment by r-ferrier** [comment]
> A few questions / thoughts.
> 
> * Should we `aria-live` the changing list? This is the main issue for me.
> * I'd prefer the styles to be in the CSS something like `.btn--active` and `.hidden` and use `toggle` on the `classList` https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle but not blocking for me.
> * I thought `[].map` returned a new array and `[].forEach` mutated existing arrays so I was surprised this worked, but it does so I'll have to look into that!

These are great suggestions! Will make those changes. AFAIK, map does return a new array, but when you mutate the objects within the array unless you create new objects you are just mutating the same things but inside a new array. I think I always default to map because you can perform chained actions on it afterwards but in this instance it's definitely not necessary so will change.

**Comment by aaaaargZombies** [comment]
strange, [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) says it returns a new array but the callback function can mutate the original array but it didn't work when I tried it.

```
> a = [1,2,3]
[ 1, 2, 3 ]
> a.map(el => el *2 )
[ 2, 4, 6 ]
> a
[ 1, 2, 3 ]
> a.map(el => el = el *2 )
[ 2, 4, 6 ]
> a
[ 1, 2, 3 ]
> 
```

This is not at all relevant to the PR sorry, just everything I thought was a lie!

**Comment by r-ferrier** [comment]
> 

I *think* this is because it's using a shallow copy inside the map, which I *think* means if it's a copy of an complex object, it's just a reference to the original object, but if it's a copy of something more like a primitive in other languages, like a number, it's a brand new one?

so if you try 

> a = [{number: 1}, {number: 2}, {number: 3}]
 [ { number: 1 }, { number: 2 }, { number: 3 } ]
> a.map(el => el.number * 2)
 [ { number: 2 }, { number: 4 }, { number: 6 } ]
> a
 [ { number: 2 }, { number: 4 }, { number: 6 } ]

**Comment by r-ferrier** [comment]
No wait i've got that wrong! It's if you reassign the value while mapping

So if you do `a.map(el => el.number * 2)` it remains unchanged but if you do `a.map(el => el.number = el.number * 2)` it changes.

**Comment by aaaaargZombies** [comment]
I think it's a combo of the shallow copy and the assignment

```
> a = [{name: 'rosie', age:1}, {name:'az', age:10}]
[ { name: 'rosie', age: 1 }, { name: 'az', age: 10 } ]
> a
[ { name: 'rosie', age: 1 }, { name: 'az', age: 10 } ]
> a.map(el => el.age * 2)
[ 2, 20 ]
> a
[ { name: 'rosie', age: 1 }, { name: 'az', age: 10 } ]
> a.map(el => el.age = el.age * 2)
[ 2, 20 ]
> a
[ { name: 'rosie', age: 2 }, { name: 'az', age: 20 } ]
> a.map(el => el = el.age * 2)
[ 4, 40 ]
> a
[ { name: 'rosie', age: 2 }, { name: 'az', age: 20 } ]
>
```

**Comment by r-ferrier** [comment]
@aaaaargZombies I've made those suggested changes, looks much cleaner. I've tested with voiceover too and the aria-live command on the outer div now alerts you when the button click changes the list.

**Comment by r-ferrier** [comment]
> I think it's a combo of the shallow copy and the assignment
> 
> ```
> > a = [{name: 'rosie', age:1}, {name:'az', age:10}]
> [ { name: 'rosie', age: 1 }, { name: 'az', age: 10 } ]
> > a
> [ { name: 'rosie', age: 1 }, { name: 'az', age: 10 } ]
> > a.map(el => el.age * 2)
> [ 2, 20 ]
> > a
> [ { name: 'rosie', age: 1 }, { name: 'az', age: 10 } ]
> > a.map(el => el.age = el.age * 2)
> [ 2, 20 ]
> > a
> [ { name: 'rosie', age: 2 }, { name: 'az', age: 20 } ]
> > a.map(el => el = el.age * 2)
> [ 4, 40 ]
> > a
> [ { name: 'rosie', age: 2 }, { name: 'az', age: 20 } ]
> >
> ```
> 
> 🙃

😀

**Review by aaaaargZombies — APPROVED** [review]
looks great to me1

**Pull request merged**
