### PR TITLE
Blog post last updated at feature

### LINKED ISSUE #74: Add first posted / last updated paragraph styling shortcode for blog posts
## Acceptance criteria

- [x] I can see when a blog post was first published
- [ ] I can see when a blog post was last updated
- [x] last updated is in italics at top of blog post, under title
- [ ] No hardcoded last update content in markdown in blogs

## Plan

needs design proposal

- [ ] Make shortcode
- [ ] Add it in where necessary

### PR DESCRIPTION
**Pull request by ivan-kocienski-gfsc**
If a blog post has a `lastmod` field in the meta headers then show that at the end of the blog content

Fixes #74 

Can be seen [here](https://ik-74-blog-last-updated-at.gfsc.pages.dev/blog/2021/hiring-rails-developer), [here](https://ik-74-blog-last-updated-at.gfsc.pages.dev/blog/2018/placecal-story-so-far/) and [here](https://ik-74-blog-last-updated-at.gfsc.pages.dev/blog/2019/hulme-greenheys-history-day/)

Looks like:

Screenshot_2023-07-04_11-53-04

@geeksforsocialchange/developers

### CODE REVIEW

**Comment by ivan-kocienski-gfsc** [comment]
Posts that need to be fixed:

- /content/blog/2021/hiring-rails-developer/index.md
- /content/blog/2018/placecal-story-so-far/index.md
- /content/blog/2019/hulme-greenheys-history-day/index.md

**Review by aaaaargZombies — CHANGES_REQUESTED** [review]
I think it would be nicer if the padding/margin matched the `p` tags

**Review by aaaaargZombies — CHANGES_REQUESTED** [review]
image

Is it possible for this to come above the footnotes, I appreciate the footnotes are pain point in hugo/markdown.

If not we might have to think about placing this somewhere else entirely

**Comment by ivan-kocienski-gfsc** [comment]
yusss i saw that as well. Unfortunately I don't think it is possible as it is part of the markdown rendering process. May want to tuck it under the title before the content?

**Comment by ivan-kocienski-gfsc** [comment]
So I moved it to below the title but now it sits below some text that is also in italics. hmmm design is hard

Screenshot_2023-07-04_14-03-11

**Review by aaaaargZombies — APPROVED** [review]
nice, I prefer it at the top anyway!

**Pull request merged**
