### PR TITLE
Make 404 page funner

### LINKED ISSUE #293: Design content for the 404 page
## Description

This is our 404 page

0d33e158 gfsc pages dev_bork

It would be nice to add some useful or entertaining info here. @aaaaargZombies made this suggestion

image

@undividual's input: 

> The only thing I'd change is make 'How did I get here' read 'Error 404: page not found' — as then the venn diagram works as a venn diagram

We just wanted to know if anyone else from the content team @honor-gfsc @rebeccawigmore had any opinions on this before we go ahead with it!

### PR DESCRIPTION
**Pull request by r-ferrier**
Fixes #293 

## Description

- Adds a venn diagram to our 404 page with silly reasons given for landing here
- Keeps the main title and adds error 404 to the centre to make sure it's clear still to all users what page this is
- Uses slightly different styling to homepage venn at mobile, to preserve look of diagram as descriptions not required

@geeksforsocialchange/developers

### CODE REVIEW

**Comment by aaaaargZombies** [comment]
@geeksforsocialchange/content maybe one of you could support with some alt text for the SVG image?

**Comment by rebeccawigmore** [comment]
I'll do this now!

**Comment by rebeccawigmore** [comment]
I've tweaked the copy because maybe a screen reader is not so pocket-based, a lot of the time? I'm not sure where to drop the code this time because it's not a usual page, so could you possibly do it for me? I'll do better next time, when I'm not so time-panicked!

[copy]

This page could not be found. Common causes include: deceased links, overzealous autocorrect and ongoing witch-based curse.

**Comment by r-ferrier** [comment]
> 

that's great, I can pick this up later today!

**Review by ivan-kocienski-gfsc — APPROVED** [review]
much better. Like Labours' spine, this page could not be found

**Pull request merged**
